/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    AWS_PROJECT_REGION: process.env.AWS_PROJECT_REGION,
    AWS_APPSYNC_GRAPHQL_ENDPOINT: process.env.AWS_APPSYNC_GRAPHQL_ENDPOINT,
    AWS_APPSYNC_REGION: process.env.AWS_APPSYNC_REGION,
    AWS_APPSYNC_AUTHENTICATION_TYPE: process.env.AWS_APPSYNC_AUTHENTICATION_TYPE,
    AWS_APPSYNC_API_KEY: process.env.AWS_APPSYNC_API_KEY,
    AWS_COGNITO_IDENTITY_POOL_ID: process.env.AWS_COGNITO_IDENTITY_POOL_ID,
    AWS_COGNITO_REGION: process.env.AWS_COGNITO_REGION,
    AWS_USERS_POOLS_ID: process.env.AWS_USERS_POOLS_ID,
    AWS_USER_POOLS_WEB_CLIENT_ID: process.env.AWS_USER_POOLS_WEB_CLIENT_ID,
    AWS_COGNITO_MFA_CONFIGURATION: process.env.AWS_COGNITO_MFA_CONFIGURATION,
    AWS_USER_FILES_S3_BUCKET: process.env.AWS_USER_FILES_S3_BUCKET,
    AWS_USER_FILES_S3_BUCKET_REGION: process.env.AWS_USER_FILES_S3_BUCKET_REGION,
  },
};

module.exports = nextConfig;
